import { z } from "zod";
import { ActivityExample } from "./Activity.js";
import crypto from "crypto";

// ACTIVITY_ENTRIES table schema
export const ActivityEntry = z.object({
  // id generated by server
  id: z.uuid().optional().default(() => crypto.randomUUID()),
  user_id: z.uuid(),
  activity_id: z.uuid(),
  start_time: z.coerce.date(),
  end_time: z.coerce.date().optional(),
  notes: z.string().optional(),
  logged_by: z.enum(['user', 'system', 'trigger']),
  ended_by: z.enum(['user', 'system', 'trigger']).optional(),
  confidence_score: z.number().min(0).max(1).optional(),
  // dates generated by db
  created_at: z.coerce.date().optional(),
  updated_at: z.coerce.date().optional(),
});

export type ActivityEntryT = z.infer<typeof ActivityEntry>;

export const EntriesExamples: ActivityEntryT[] = [
  {
    id: crypto.randomUUID(),
    user_id: crypto.randomUUID(),
    activity_id: ActivityExample.id,
    start_time: new Date('2025-11-04T08:00:00Z'),
    end_time: new Date('2025-11-04T09:00:00Z'),
    notes: 'Felt great, completed all exercises',
    logged_by: "user",
    confidence_score: 1,
  },
  {
    id: crypto.randomUUID(),
    user_id: crypto.randomUUID(),
    activity_id: ActivityExample.id,
    start_time: new Date('2025-11-05T08:00:00Z'),
    end_time: new Date('2025-11-05T09:00:00Z'),
    notes: 'Skipped a few exercises, felt tired',
    logged_by: "user",
    confidence_score: 0.8,
  },
  {
    id: crypto.randomUUID(),
    user_id: crypto.randomUUID(),
    activity_id: ActivityExample.id,
    start_time: new Date('2025-11-06T08:00:00Z'),
    end_time: new Date('2025-11-06T09:00:00Z'),
    logged_by: "user",
    confidence_score: 0.5,
  }

];